name: nlp_sti_tutorials
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - backcall=0.2.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - cpython=3.9.22
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.8
  - debugpy=1.8.11
  - decorator=5.2.1
  - entrypoints=0.4
  - executing=2.2.0
  - ffmpeg=4.3
  - filelock=3.17.0
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.13.1.3
  - libcurand=10.3.9.90
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.2.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - requests=2.32.3
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - accelerate==1.6.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.11.18
    - aiosignal==1.3.2
    - aiosqlite==0.21.0
    - annotated-types==0.7.0
    - anyio==4.9.0
    - async-timeout==4.0.3
    - attrs==25.3.0
    - banks==2.1.2
    - beautifulsoup4==4.13.4
    - click==8.1.8
    - colorama==0.4.6
    - dataclasses-json==0.6.7
    - datasets==3.5.1
    - deprecated==1.2.18
    - dill==0.3.8
    - dirtyjson==1.0.8
    - distro==1.9.0
    - docling==2.33.0
    - docling-core==2.31.1
    - docling-ibm-models==3.4.3
    - docling-parse==4.0.1
    - easyocr==1.7.2
    - et-xmlfile==2.0.0
    - eval-type-backport==0.2.2
    - exceptiongroup==1.2.2
    - faiss-cpu==1.11.0
    - filetype==1.2.0
    - frozenlist==1.6.0
    - fsspec==2025.3.0
    - greenlet==3.2.1
    - griffe==1.7.3
    - h11==0.16.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - httpx-sse==0.4.0
    - huggingface-hub==0.30.2
    - imageio==2.37.0
    - ipywidgets==8.1.7
    - jiter==0.10.0
    - joblib==1.4.2
    - jsonlines==3.1.0
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - jsonref==1.1.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2025.4.1
    - jupyterlab-widgets==3.0.15
    - langchain==0.3.24
    - langchain-community==0.3.23
    - langchain-core==0.3.56
    - langchain-text-splitters==0.3.8
    - langsmith==0.3.38
    - latex2mathml==3.78.0
    - lazy-loader==0.4
    - llama-cloud==0.1.26
    - llama-cloud-services==0.6.34
    - llama-index==0.12.44
    - llama-index-agent-openai==0.4.11
    - llama-index-cli==0.4.3
    - llama-index-core==0.12.44
    - llama-index-embeddings-huggingface==0.5.5
    - llama-index-embeddings-openai==0.3.1
    - llama-index-indices-managed-llama-cloud==0.7.7
    - llama-index-instrumentation==0.2.0
    - llama-index-llms-openai==0.4.7
    - llama-index-llms-openai-like==0.4.0
    - llama-index-llms-together==0.3.2
    - llama-index-multi-modal-llms-openai==0.5.1
    - llama-index-program-openai==0.3.2
    - llama-index-question-gen-openai==0.3.1
    - llama-index-readers-file==0.4.9
    - llama-index-readers-llama-parse==0.4.0
    - llama-index-workflows==1.0.1
    - llama-parse==0.6.34
    - lxml==5.4.0
    - markdown-it-py==3.0.0
    - marko==2.1.3
    - marshmallow==3.26.1
    - mdurl==0.1.2
    - mpire==2.10.2
    - multidict==6.4.3
    - multiprocess==0.70.16
    - mypy-extensions==1.1.0
    - ninja==1.11.1.4
    - nltk==3.9.1
    - openai==1.91.0
    - opencv-python-headless==4.11.0.86
    - openpyxl==3.1.5
    - orjson==3.10.16
    - outcome==1.3.0.post0
    - packaging==24.2
    - pandas==2.2.3
    - pluggy==1.6.0
    - propcache==0.3.1
    - psutil==7.0.0
    - pyarrow==20.0.0
    - pyclipper==1.3.0.post6
    - pydantic==2.11.7
    - pydantic-core==2.33.2
    - pydantic-settings==2.9.1
    - pylatexenc==2.10
    - pymupdf==1.25.5
    - pypdf==5.6.1
    - pypdf2==3.0.1
    - pypdfium2==4.30.1
    - python-bidi==0.6.6
    - python-docx==1.1.2
    - python-dotenv==1.1.0
    - python-pptx==1.0.2
    - pytz==2025.2
    - rank-bm25==0.2.2
    - referencing==0.36.2
    - regex==2024.11.6
    - requests-toolbelt==1.0.0
    - rich==13.9.4
    - rpds-py==0.25.1
    - rtree==1.4.0
    - safetensors==0.5.3
    - scikit-image==0.24.0
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - selenium==4.32.0
    - semchunk==2.2.2
    - sentence-transformers==4.1.0
    - setuptools==80.9.0
    - shapely==2.0.7
    - shellingham==1.5.4
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - soupsieve==2.7
    - sqlalchemy==2.0.40
    - striprtf==0.0.26
    - sympy==1.13.1
    - tabulate==0.9.0
    - tenacity==9.1.2
    - threadpoolctl==3.6.0
    - tifffile==2024.8.30
    - tiktoken==0.9.0
    - together==1.4.6
    - tokenizers==0.21.1
    - tqdm==4.67.1
    - transformers==4.51.3
    - trio==0.30.0
    - trio-websocket==0.12.2
    - typer==0.15.4
    - typing-inspect==0.9.0
    - typing-inspection==0.4.0
    - tzdata==2025.2
    - websocket-client==1.8.0
    - widgetsnbextension==4.0.14
    - wrapt==1.17.2
    - wsproto==1.2.0
    - xlsxwriter==3.2.3
    - xxhash==3.5.0
    - yarl==1.20.0
    - zstandard==0.23.0
